### ISSUE TITLE
[fr] Deux fois "ce genre" dans la même phrase

### ISSUE THREAD

**Issue by ghost** [Deevad/peppercarrot_ep23_translation#1]
Page 5:

> **Ce genre** de truc aurait peut-être marché sur nous avant, mais maintenant on n'est plus assez idiots pour tomber dans **ce genre** de piège !

Ça me semble un peu répétitif.

**Comment by calimeroteknik** [comment]
Effectivement, ça serait mieux comme :
> Ce truc-là aurait peut-être marché sur nous avant, mais maintenant on n'est plus assez idiots pour tomber dans ce genre de piège !

**Comment by Deevad** [comment]
@M1dgard : Merci pour la relecture, je suis totalement d'accord. 

@calimeroteknik  : belle solution, merci. Je vais intégrer ça.
