### ISSUE TITLE
[nl] Proofread

### ISSUE THREAD

**Issue by ghost** [Deevad/peppercarrot_ep23_translation#10]
- [x] Fix stupid copying errors (add missing *d*, remove excessive *toch*, 274bd59bd108cc0ee9aeb30bdc8fa0f0fb9e5acb)
- [x] P3: Improve the 24/7 phrase (bfb7bb9e5255e989f9524b6a7288a4ffaa705d87 and ea6c3878aa605b84d54c087e93d619b23fa4b264)
- [x] P4: Improve the phrase about non-cumulativity (73073d52099dacab22d3f5257a67fae1b7cc5d39)
- P6: Improve the phrase about doing effort
  - [x] Correct *weer/terug* anomaly (adb8410f008ef9c5e5c82179fa7d0a443f760679)
  - [x] Ask David what he originally meant (https://github.com/Deevad/peppercarrot_ep23_translation/issues/10#issuecomment-321391361)
  - [x] Adapt to David's reply

**Comment by Willem3141** [comment]
Thanks for translating! A few proofreading comments...

* page 3: *ik ben de Succesgeest, elke dag toch tot uw dienst, vierentwintig uur op vierentwintig!* -> remove *toch*, also *vierentwintig uur op vierentwintig* sounds strange in nl_NL; I would prefer *vierentwintig uur per dag, zeven dagen per week*

* page 4: *aanbod niet cumuleerbaar*: in nl_NL *niet geldig op lopende aanbiedingen* is more common, but both are understandable to me

* page 6: *Goekope trucjes doorzien, terug moeite leren doen …*: add *d* in *goedkope*. Furthermore I am confused by the translation of the second part of the sentence, *terug moeite leren doen*. However, I am also confused by the source languages: the English is ‘appreciate the value of effort’ - *de waarde van succes waarderen* and the French is ‘reprendre le goût de l'effort…’ - *de smaak van succes weer te pakken krijgen* or something? That seems quite different... so I don't really know what to do with this sentence.

I can commit them to master if you agree with those 😃

**Comment by ghost** [comment]
> *toch*, missing *d* in *goedkope*

Oops! Those were absolutely not intended.

* page 3: I had that originally too and changed it for spacing, otherwise the lines are of very uneven length. It may be good to do some balloon wizardry there, I don't really like the phrase as it is now either.

* page 4: in nl_BE I've never seen *niet geldig op lopende aanbiedingen*, but it is understandable too.

* page 6: Just something that says something along the lines of appreciating effort ¯\\\_(ツ)\_/¯

**Comment by ghost** [comment]
Maybe `s/aanbod niet cumuleerbaar/niet cumuleerbaar met andere acties/`?

**Comment by Willem3141** [comment]
* page 3: is this okay, then?

![Balloon wizardry!](https://user-images.githubusercontent.com/7533280/29144992-6219d934-7d5b-11e7-9c13-040a296c48e0.png)

* page 4: `niet cumuleerbaar met andere acties` sounds strange to me (je kunt niet iets cumuleren met iets anders; meerdere dingen cumuleren zelf - ten minste volgens mijn taalgevoel) - Then maybe `niet combineerbaar met andere acties`. But as I said, the original works, too

* page 6: right, I guess I am too young for those profound lessons about life 😉 Suggestion: *leren moeite te doen om resultaat te bereiken*? Maybe too formal...

**Comment by ghost** [comment]
What I mean with "terug moeite leren doen" is "relearning to do effort". Probably overly influenced by the French *re-*.

Btw "reprendre le goût de l'effort…" means "de smaak van **moeite** weer opnemen", not of "succes"

**Comment by M1dgard** [comment]
> I guess I am too young for those profound lessons about life :wink:

I'm younger than you so that would make me even *too-young*-er :p

**Comment by ghost** [comment]
> page 3

Perfect. Although... didn't you now introduce a tautology yourself? :wink:

**Comment by Willem3141** [comment]
> "relearning to do effort"

Okay, in that case let's leave the original translation. Maybe replace *terug* by *weer*, but maybe that is a nl_NL-ism.

> "reprendre le goût de l'effort…" betekent trouwens "de smaak van **moeite** weer opnemen", niet van "succes"

... I mistranslate the only French word in that sentence that is the same as the English word. Typical.

**Comment by ghost** [comment]
"Niet combineerbaar met andere acties" sounds good. I'd settle for that.

---

> >  "relearning to do effort"
>
> Okay, in that case let's leave the original translation

Hmm, I'm not sure that's what David means. What do you mean @Deevad?
1. Has Pepper lost the taste of effort and does she believe that refinding it is part of growing up? (**re**prendre)
2. Or is it just learning to do effort, without the implication that she could do it before and needs to relearn it?

**Comment by ghost** [comment]
> Maybe replace *terug* by *weer*, but maybe that is a nl_NL-ism.

Ah, the classic *terug* vs *weer* vs *opnieuw*. Those almost always feel interchangeable around here even though in Standard Dutch they aren't. Feel free to change at will.

**Comment by ghost** [comment]
> Page 3: "ik ben de Succesgeest, elke dag tot uw dienst, vierentwintig uur per dag, zeven dagen per week!*"

Proposition: `s/elke dag/steeds/` (or `s/elke dag/immer/` for extra bombast)

(↑ Look! This will lessen the visibility of the tautology! \o/ )

**Comment by Willem3141** [comment]
Done!

> (↑ Look! This will lessen the visibility of the tautology! \o/ )

And of the contradiction. Every day, 7 days per week... except for weekends. Heh 😛

**Comment by ghost** [comment]
I've made a todo list in the OP to track progress. Seems like we're done apart from the effort thingy. Or did I miss something?

**Comment by Willem3141** [comment]
I think we are good to go; we can change the life lesson later if needed 😃

**Comment by Deevad** [comment]
Hey @M1dgard and @Willem3141 ; thank you for the work on the [nl] translation! 


> Hmm, I'm not sure that's what David means. What do you mean @Deevad?
> 1. Has Pepper lost the taste of effort and does she believe that refinding it is part of growing up? (reprendre)
> 2. Or is it just learning to do effort, without the implication that she could do it before and needs to relearn it?

It's more similar to (1).  Just keep in mind Pepper never really had the taste to do effort in general xD  She lies a bit to herself thinking she lost it and will refind it. For sure, she lost it on a recent past in the comic: on the roof under the rain. At the end of the story, her body is back in action. Pepper is the master of remotivational self-dialog ! :-D

**Comment by ghost** [comment]
@Deevad Thanks for this clarification! It will really help us to convey the message you intended.
