### ISSUE TITLE
The genie doesn't introduce himself correctly

### ISSUE THREAD

**Issue by Deevad** [Deevad/peppercarrot_ep23_translation#2]
A feedback from @agryson : The genie enter the scene without a simple hello or annuncing what his speech will be.

Proposal: 
```
- "Hello! Please allow me to introduce myself:" 
- "Bonjour! Permettez moi de me présenter:"  
```
+adding new speechbubbles

**Comment by Deevad** [comment]
test:

![2017-08-01_screenshot_085009](https://user-images.githubusercontent.com/4021867/28812754-7cc6ca38-7696-11e7-9e05-fec473a14a9c.png)

**Comment by calimeroteknik** [comment]
typography fix (hyphen/fine insecable spaces): Bonjour ! Permettez-moi de me présenter !

**Comment by calimeroteknik** [comment]
Actually, maybe use a colon:
```
Bonjour !
Permettez-moi de me présenter :
je suis le Génie du Succès, …
```
