### ISSUE TITLE
Bug in polish translation: Deus ex machina

### ISSUE THREAD

**Issue by Deevad** [Deevad/peppercarrot_ep23_translation#20]
Hey,
Here is a new report I received on Facebook private message:
![2017-10-28_screenshot_005639](https://user-images.githubusercontent.com/4021867/32128081-6923680e-bb7b-11e7-833f-4fc82ea0aace.png)

**Comment by WorkingWarrior** [comment]
Hey, David, thanks for notifying me! I'll read it once again in polish language and decide what to do ;)

**Comment by Deevad** [comment]
@WorkingWarrior  :+1:  Thank you!

**Comment by WorkingWarrior** [comment]
I changed it to „deus ex machina” ;) Thank you once again!

**Comment by Deevad** [comment]
Thank you again @WorkingWarrior  !
